### ISSUE TITLE
Intensity of electric brake system

### ISSUE THREAD

**Issue by LaserPew** [M4GNV5/DocGreenESA5000-Dashboard#1]
Hey,

nice work on your dashboard and all the reverse engineering! 

I don't know how relevant my question is to your project but I was wondering if you think that it would be possible to somehow adjust the electric brake intensity in firmware? My experience with the scooter so far is that the brake is really sudden as if the brake potentiometer is just binary (even though in your protocol documentation it says that the brake lever ranges from 2C to B5). Do you have the same experience or is it just me (I have the ESA 1919, but as far as I can tell the differences are just appearance).

Greetings

**Comment by M4GNV5** [comment]
Hey,

there are two brakes: the electric brake and the disc brake. One big issue is that pulling the disc brake lever also brakes with 100% on the electric brake. A common mod is to unplug the sensor making the brake lever only operate the disc brake. In my custom dashboard the mechaical lever makes the [electric brake operate at 40%](https://github.com/M4GNV5/DocGreenESA5000-Dashboard/blob/master/DocGreenDisplay/DocGreenDisplay.ino#L531-L539)

The electric brake lever itself can be controled by pushing it ever so gently. Some people stated they feel like the electric brake is worse with a new scooter but is better dosable later. Could just be them getting used to controlling it though.

**Comment by camp0s** [comment]
Sorry for opening this old issue, but I found a nice solution for the switch-brake:

the cable has two wires going to the dashboard red-blue. The Voltage (on the red) reads 4.4V, and when the brake lever is pushed (and the button activated) it reads "0v", maning a pull-down effect (and, maybe, a small voltage partitioning on the dash side in standby).

In that case (0V on the input) the Roller is breaking too hard. The objective it to keep the voltage UP and reduce the pull-down: it is simply accomplished **inserting a 1K resistor on the red wire**, thus influencing the pull-down circuit and allowing a 3.6V on the board's input, when the brake lever is pressed (10K is too much, the roller is not breaking at all, 100ohm is too low, voltage drops too much).

Now, when you brake with the lever, you can feel a gentle (but constant) E-brake slow-down - if more stopping power is required, lean on the back and dose the disk-brake: you can slide, while NOT locking the front wheel.

This mod is so simple, yet so effective! I hope it could help somebody.
(it's odd that the ESA is reading this input in a "analog way" (albeit inverted from the HALLs' logic), and they didn't cheap out with a DIG_in).

**Comment by kaiomatico** [comment]
@camp0s  could you maybe provide a picture or a link to a tutorial? Thank you so much for the information, I was always hoping for such a mod

**Comment by camp0s** [comment]
> 
> 
> @camp0s could you maybe provide a picture or a link to a tutorial? Thank you so much for the information, I was always hoping for such a mod

I.. resealed the dash with the leftover of the glue, but the mod is really simple:

_ find the wire from the switch of the brake, in my "Explorer 1919" it's red-blu
_ cut 1cm (no more!) of the red wire out, on the cable from the button to the connector
_ patch it with a 1kohm resistor (effectively replacing the piece of wire)

So, some ASCII art (like it's the late 80's again and 1200BPS modems were killing it):

DASH----wire---socket <-plugged-> plug----wire---brake_button
                                                                   ^-- remove the 1cm of cable there and solder the resistor

I might also add I tuned also the e-brake, the red left level.. but that took already 3-4 components to do it right, might take some screenshots soon :)

**Comment by kaiomatico** [comment]
I made a photo of the installation on my ESA 5000  
![image](https://user-images.githubusercontent.com/8037196/109394125-a392f480-7925-11eb-96a9-12cd2fa5a22f.png)
Thank you for the idea with the resistor - but I think it is still braking pretty hard, I guess I will try 2K and 3K resistors next :+1:

**Comment by camp0s** [comment]
> 
> 
> I made a photo of the installation on my ESA 5000

Hi, really strange! Do you have a multimeter? can you measure the voltage on the connector in the photo, when connected, and tell us the normal voltage value and when you depress the button? On mine no action is 4.4V, and when I brake 3.6V.
To measure you stick the probes in the 2 small "windows" you see on the connector.

I used a 10K resistor (as a test) and the "braked" voltage was 4.3V and the brake was not activating at all (voltage too high).
With no resistor the voltage was 0V.

I tested in the garage, so a closed space, and the breaking power was reaaaaally soft.

Additional test: let the wheel freewheel holding the scooter up, the breake with the lever: with no resistor the wheel stops abruptly AND spins backward due to the intensity of the brake power.

With the resistor the wheel comes to a normal stop, with no backslash.
