### ISSUE TITLE
Schematics, wiring diagram or better documentation

### ISSUE THREAD

**Issue by karlitos** [M4GNV5/DocGreenESA5000-Dashboard#2]
Hello Jakob, incredible work you did here 👍 I would love to build this display for me and maybe also to contribute and participate on the development. Would you be so kind and improve your documentation, so it includes detailed schematics or wiring diagram and also part listing (arduino board type, LCD module ... )

**Comment by M4GNV5** [comment]
Hey,

The most important wiring is the bus wiring, which i took from [m365_dashboard](https://github.com/augisbud/m365_dashboard). Additionally i added latching buttons allowing to disable the bus connection and flash the arduino. and a big button power on/off, light and eco mode.

![](https://camo.githubusercontent.com/a912641249173768ae60670e843c62294d06da4f/68747470733a2f2f656c656374726f2e636c75622f646174612f666f72756d2f6d657373616765732f34323633312f696d616765732f31313636302d313238302e6a7067)

I guess i can create a schematic, but on the long run we plan to develop a PCB replacement which can be freely programmed.
you might want to join the ESA5k hacking group on telegram: https://t.me/ESA_5000_Hacking

**Comment by karlitos** [comment]
Many thanks four your reply. I will first start with ordering some oled display and and aduino mini board. I found some 0.91 inch 128x32 OLED on Amazon with SSD1306 driver - looks similar to yours. Would be great to know how to connect it to the ESA board.

**Comment by M4GNV5** [comment]
Hey,

i added a simple circuit to the readme created using https://www.circuit-diagram.org/.
I hope that explains how to connect the controller & inputs to the arduino.
