### ISSUE TITLE
Which connector are they using for the dashboard to connect to the scooter?

### ISSUE THREAD

**Issue by CzokNorris** [M4GNV5/DocGreenESA5000-Dashboard#3]
Hi, 
does anyone know what the name of the 4-pin connector is, that is used to connect the dashboard to the motor-controller in the steering column?
Its not a JST PH
But it is also 2.0mm and 4 pin.

**Comment by M4GNV5** [comment]
Hey,

in the telegram group someone once said it should be a "JST PAP-04V-S".
![image](https://user-images.githubusercontent.com/5504713/84998163-c55d9a00-b14f-11ea-9a97-af8ee70c1ebf.png)

Others said they bought [4Pin 2.0 PH 2.0mm Mini JST](https://www.ebay.de/itm/183101792371?ul_noapp=true). After removing the noses those should work too.

**Comment by M4GNV5** [comment]
There also seem to be these: [HY-4A](https://lcsc.com/product-detail/Wire-To-Board-Wire-To-Wire-Connector_Boom-Precision-Elec-HY-4A_C146064.html) and [HY-4Y](https://lcsc.com/product-detail/Rectangular-Connectors-Housings_BOOMELE-Boom-Precision-Elec-HY-4Y_C146075.html)

**Comment by carlosfd1** [comment]
It is called a "Grove" Connector and it is available at seeedstudio.com

**Comment by M4GNV5** [comment]
Indeed, these seem to be the same ones: [male (scooter side)](https://www.seeedstudio.com/Grove-Universal-4-Pin-Buckled-20cm-Cable-5-PCs-pack.html) / [female (dashboard side)](https://www.seeedstudio.com/Grove-Universal-4-pin-connector.html)
