### ISSUE TITLE
Controlling the dashboard buzzer

### ISSUE THREAD

**Issue by locomarco** [M4GNV5/DocGreenESA5000-Dashboard#4]
Do you think it is possible to make use of the dashboards buzzer?
I think the controller is doing that, when the immobilizer / lock mode is enabled.

**Comment by M4GNV5** [comment]
Afaik the Buzzer is used for reporting error codes. So setting an error code could work.

Not sure what the vanilla dash does when locked. In the optimal case there might be a bit set by the controller when immobilizer is enabled and the scooter is moved causing the dashboard to buzz. But i neither have any protocol dumps nor a working vanilla dash to test that :frowning_face: 
Maybe someone can do a bus dump of lock->push->unlock or something.

**Comment by locomarco** [comment]
The original esa Dashboard beeps once/twice when activating/deactivating lock mode and beeps in short intervals when you try to move the scooter.
Unfortunately i don't have proper hardware to dump Bus messages myself. 

I am just looking for a way to get some feedback when i for example set a new max speed.
Instead of the buzzer, i now just acitvate eco mode for a second, so the green led confirms the action. 

Setting an error code would probably be a good idea, too. 
I might try that soon. 

Thank you 🙂👍
