### ISSUE TITLE
DocGreenESA5000 Bluetooth Protocol

### ISSUE THREAD

**Issue by thisismck** [M4GNV5/DocGreenESA5000-Dashboard#5]
Do you have any work for original bluetooth protocol or do you plan to ad bluetooth for using with same morobot app?

**Comment by M4GNV5** [comment]
The ESP32 has support for BLE, so in theory the protocol could be implemented. Currently i have no plans for Bluetooth functionality. Using WiFi & a Webinterface is cross plattform (Android / iOS / Desktop / ...) and does not require the user to install any app from a third party vendor.
However the hardware support is available so it could be added as a software update later. Feel free to implement the Bluetooth protocol and send a pull request :smiley: :stuck_out_tongue:

**Comment by M4GNV5** [comment]
Hey,

26e979f9854659347671fbfe6ef56f634b9f8add implements the original M365 Protocol. I havn't tested it with many apps yet, but it definitely works with the M365 Plus app for iOS. Of course not all fields are supported but some are (range, speed, odometer, ...).
A screenshot of the app connected to my scooter:

![](https://i.m4gnus.de/12f61d.png)
