### ISSUE TITLE
missing file "webinterface/bundle.hpp"

### ISSUE THREAD

**Issue by thisismck** [M4GNV5/DocGreenESA5000-Dashboard#8]
Hello M4GNV5, I cannot find bundle.hpp file. I want to try this codes for my scooter. And moreover, can you share arduino version bcs i dont want to use bluetooth and wifi and esp32 devkitc too big for dashboard place

**Comment by M4GNV5** [comment]
Hey,

the `bundle.hpp` is generated using [generate-bundle.py](https://github.com/M4GNV5/DocGreenESA5000-Dashboard/blob/master/DocGreenDisplay/webinterface/generate-bundle.py). It basically combines the html, js and css files to a single file, gzips it and converts it to an `uint8_t` array.

The current upstream code uses some ESP32 specific libraries even for core functionality (e.g. the `Preferences` library), not just for WiFi and BLE. You can however try an older commit from this repo, namely [973d3b0ff8db8cf06b1be155ae9004223ea864b7](https://github.com/M4GNV5/DocGreenESA5000-Dashboard/tree/973d3b0ff8db8cf06b1be155ae9004223ea864b7) should work on an Arduino board and allow most functionality like tuning, displaying stats etc.

With git CLI: `git checkout 973d3b0ff8db8cf06b1be155ae9004223ea864b7`
Otherweise just download the [code of the commit from this link](https://github.com/M4GNV5/DocGreenESA5000-Dashboard/archive/973d3b0ff8db8cf06b1be155ae9004223ea864b7.zip)
